# tasks file
---
- name: create (download) directory
  ansible.builtin.file:
    path: "{{ gosu_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - gosu-install-download
    - gosu-install-download-directory

- name: download
  ansible.builtin.get_url:
    url: "https://github.com/tianon/gosu/releases/download/{{ gosu_version }}/gosu-{{ gosu_machine_map[ansible_machine] }}"
    dest: "{{ gosu_downloads_path }}/gosu-{{ gosu_machine_map[ansible_machine] }}-{{ gosu_version }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - gosu-install-download
    - gosu-install-download-get

- name: install
  ansible.builtin.file:
    src: "{{ gosu_downloads_path }}/gosu-{{ gosu_machine_map[ansible_machine] }}-{{ gosu_version }}"
    dest: "{{ gosu_install_prefix }}/gosu"
    state: link
    force: true
  tags:
    - gosu-install-install
    - gosu-install-install-symlink
